; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


;board_build.partitions = min_spiffs.csv
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
default_envs = saola, kaluga

[env]
platform = espressif32
framework = arduino
;board_build.partitions = min_spiffs.csv
lib_deps =
  adafruit/Adafruit BME280 Library
  knolleary/PubSubClient
  adafruit/Adafruit ST7735 and ST7789 Library
  adafruit/Adafruit GFX Library
  bblanchon/ArduinoJson@^6

[env:saola]
build_flags = 
	-D ESP32_SAOLA
	-D TFT_CS=11
	-D TFT_DC=13
	-D TFT_MOSI=9
	-D TFT_CLK=15
	-D TFT_RST=16
	-D TFT_BL=6
board = esp32-s2-saola-1
monitor_speed = 115200
upload_protocol = espota
upload_port = 192.168.178.89

[env:kaluga]
build_flags = 
	-D ESP32_KALUGA
	-D TFT_CS=11
	-D TFT_DC=13
	-D TFT_MOSI=9
	-D TFT_CLK=15
	-D TFT_RST=16
	-D TFT_BL=6
board = esp32-s2-kaluga-1
monitor_speed = 115200
